global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sdn_controller'
    static_configs:
      - targets: ['ryu:8000']
    scrape_interval: 5s
    scrape_timeout: 4s