# Prometheus configuration file

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
scrape_configs:
  - job_name: 'sdn_controller'
    static_configs:
      - targets: ['ryu:9090']
    scrape_interval: 5s
    scrape_timeout: 4s